name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: APP

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep -m 1 -E '^\s*MARKETING_VERSION' PinConfigurator.xcodeproj/project.pbxproj | awk -F' = ' '{ print $2 }' | tr -d ';' | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build Debug
        run: xcodebuild -jobs 1 -configuration Debug -arch x86_64 SYMROOT=$PWD/build
      - name: Build Release
        run: xcodebuild -jobs 1 -configuration Release -arch x86_64 SYMROOT=$PWD/build
      - name: Zip Build
        run: zip -r PinConfigurator.zip build/Release build/Debug
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: PinConfigurator.zip
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PinConfigurator.zip
          tag: ${{ env.VERSION }}
          overwrite: true
          file_glob: true
